apiVersion: 1
deleteDatasources:
  - name: InfluxDB
    orgId: 1
datasources:
  - name: InfluxDB
    type: influxdb
    orgId: 1
    url: http://clab-lab21-influxdb:8086
    user: gnmic
    password: gnmic
    database: telemetry
    editable: true
