version: '3' 

networks:
  gnmic-net:
    driver: bridge

services:
  gnmic-collector1: &gnmic
    image: ghcr.io/karimra/gnmic:latest
    container_name: gnmic-collector1
    volumes:
      - ./gnmic-collector.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    environment:
      - GNMIC_API=":7890"
      - GNMIC_CLUSTERING_INSTANCE_NAME="gnmic-collector1"
      - GNMIC_CLUSTERING_SERVICE_ADDRESS="gnmic-collector1"
    networks:
      - gnmic-net
    ports:
      - 7890:7890
    depends_on:
      - nats

  gnmic-collector2:
    <<: *gnmic
    container_name: gnmic-collector2
    environment:
      - GNMIC_API=":7891"
      - GNMIC_CLUSTERING_INSTANCE_NAME="gnmic-collector2"
      - GNMIC_CLUSTERING_SERVICE_ADDRESS="gnmic-collector2"   
    ports:
      - 7891:7891

  gnmic-collector3: 
    <<: *gnmic
    container_name: gnmic-collector3
    environment:
      - GNMIC_API=":7892"
      - GNMIC_CLUSTERING_INSTANCE_NAME="gnmic-collector3"
      - GNMIC_CLUSTERING_SERVICE_ADDRESS="gnmic-collector3"   
    ports:
      - 7892:7892

  gnmic-relay1:
    <<: *gnmic
    container_name: gnmic-relay1
    volumes:
      - ./gnmic-relay.yaml:/app/gnmic.yaml
    environment:
      - GNMIC_OUTPUTS_OUTPUT1_LISTEN="gnmic-relay1:9804"   
    ports:
      - 9804:9804
    depends_on:
      - nats
      - consul-agent
  
  gnmic-relay2:
    <<: *gnmic
    container_name: gnmic-relay2
    volumes:
      - ./gnmic-relay.yaml:/app/gnmic.yaml
    environment:
      - GNMIC_OUTPUTS_OUTPUT1_LISTEN="gnmic-relay2:9805"   
    ports:
      - 9805:9805
    depends_on:
      - nats
      - consul-agent
  
  gnmic-relay3:
    <<: *gnmic
    container_name: gnmic-relay
    volumes:
      - ./gnmic-relay3.yaml:/app/gnmic.yaml
    ports:
      - 9806:9806
    depends_on:
      - nats
      - consul-agent
                    
  consul-agent:
    image: consul:latest
    container_name: consul
    networks:
      - gnmic-net
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    ports:
      - 9090:9090
    networks:
      - gnmic-net

  nats:
    image: 'nats:latest'
    container_name: nats
    networks:
      - gnmic-net    
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      
volumes:
  prometheus-data:
