name: lab14

topology:
  defaults:
    kind: srl

  kinds:
    srl:
      image: ghcr.io/nokia/srlinux

  nodes:
    spine1:
      type: ixr6
    spine2:
      type: ixr6
    leaf1:
    leaf2:
    leaf3:
    leaf4:

    gnmic:
      kind: linux
      image: ghcr.io/karimra/gnmic:latest
      binds:
        - ./gnmic.yaml:/app/gnmic.yaml:ro
        - /var/run/docker.sock:/var/run/docker.sock
      cmd: '--config /app/gnmic.yaml --log subscribe'
    
    consul-agent:
      kind: linux
      image: consul:latest
      ports:
        - 8500:8500
        - 8600:8600/udp
      cmd: 'agent -server -ui -bind=127.0.0.1 -node=server-1 -bootstrap-expect=1 -client=0.0.0.0'
    
    prometheus:
      kind: linux
      image: prom/prometheus:latest
      user: 65534:65534
      ports:
        - 9090:9090
      binds:
        - ./prometheus/:/etc/prometheus/
      cmd: |
        --config.file=/etc/prometheus/prometheus.yaml
        --web.console.libraries=/usr/share/prometheus/console_libraries
        --web.console.templates=/usr/share/prometheus/consoles
        --log.level=debug

    grafana:
      kind: linux
      image: grafana/grafana:latest
      binds:
        - grafana/datasources/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml:ro
        #- grafana/dashboards/:/var/lib/grafana/dashboards
      ports:
        - 3000:3000
        
  links:
    # spine1 links
    - endpoints: ["spine1:e1-1", "leaf1:e1-1"]
    - endpoints: ["spine1:e1-2", "leaf2:e1-1"]
    - endpoints: ["spine1:e1-3", "leaf3:e1-1"]
    - endpoints: ["spine1:e1-4", "leaf4:e1-1"]
    # spine2 links
    - endpoints: ["spine2:e1-1", "leaf1:e1-2"]
    - endpoints: ["spine2:e1-2", "leaf2:e1-2"]
    - endpoints: ["spine2:e1-3", "leaf3:e1-2"]
    - endpoints: ["spine2:e1-4", "leaf4:e1-2"]

