version: '3' 

networks:
  gnmic-net:
    driver: bridge

services:
  gnmic-collector: &gnmic
    image: ghcr.io/karimra/gnmic:latest
    container_name: gnmic-collector
    volumes:
      - ./gnmic-collector.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    networks:
      - gnmic-net
    depends_on:
      - nats

  gnmic-relay1:
    <<: *gnmic
    container_name: gnmic-relay1
    volumes:
      - ./gnmic-relay1.yaml:/app/gnmic.yaml
    ports:
      - 9804:9804
    depends_on:
      - nats
      - consul-agent

  gnmic-relay2:
    <<: *gnmic
    container_name: gnmic-relay2
    volumes:
      - ./gnmic-relay2.yaml:/app/gnmic.yaml
    depends_on:
      - nats
      - influxdb

  consul-agent:
    image: consul:latest
    container_name: consul
    networks:
      - gnmic-net
    ports:
      - 8500:8500
      - 8600:8600/udp
    command: agent -server -ui -node=server-1 -bootstrap-expect=1 -client=0.0.0.0
    
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--log.level=debug'
    ports:
      - 9090:9090
    networks:
      - gnmic-net

  nats:
    image: 'nats:latest'
    container_name: nats
    networks:
      - gnmic-net    
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    networks:
      - gnmic-net
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      - INFLUXDB_DATA_ENGINE=tsm1
      - INFLUXDB_REPORTING_DISABLED=false
      - INFLUXDB_USER=gnmic
      - INFLUXDB_USER_PASSWORD=gnmic
      - INFLUXDB_DB=telemetry
    volumes:
      - influx-storage:/var/lib/influxdb

volumes:
  prometheus-data:
  influx-storage:
